products:
  - name: "Galea 630 Boat Rental"
    slug: "galea-galeon-630-boat-rental-ibiza"
    category: "boat-rental" # Referencia al ID del documento de categoría
    
    # Visibility settings
    showOnHome: true
    
    # Pricing options
    price: 490
    showFromPrice: true
    priceSubtitle: "Half Day"
    
    # Basic product details
    duration: "4 Hours"
    shortDescription: "Ideal for walks with family or friends, this boat will make you spend beautiful days at sea! Perfect for exploring Ibiza's coast."
    highlights:
      - "6.3m boat with Yamaha 150 HP engine"
      - "Shower and swim ladder included"
      - "Can be rented with or without skipper"
      - "Perfect for the north coast of Ibiza"
    
    # Product specific details
    productType: "rental"
    bookButtonText: "Book This Boat"
    tripSummary: "Half-day boat rental experience"
    specificTime: "11:30 AM, 12:30 PM, 4:00 PM"
    departurePoint: "San Antonio Port, Ibiza"
    capacity: "6 persons (including skipper)"
    season: "May to October"
    limitedAvailability: "Book at least 48 hours in advance recommended"
    customDetails:
      - label: "Boat Model"
        value: "Galea - Galeon 630"
      - label: "Year"
        value: "2018"
      - label: "Length"
        value: "6.3 meters"
      - label: "Width"
        value: "2.4 meters"
      - label: "Draft"
        value: "1.2 meters"
        
    # Features & amenities
    features:
      - key: "Length"
        value: "6.3 meters"
      - key: "Width"
        value: "2.4 meters"
      - key: "Motor"
        value: "Yamaha 150 HP"
      - key: "Capacity"
        value: "6 persons"
      - key: "Number of cabins"
        value: "1"
    includes:
      - "Shower"
      - "Swim ladder"
      - "Table"
      - "Port fees"
      - "VAT and insurance"
    notIncludes:
      - "Fuel (estimated 90€ per half day)"
      - "Skipper (optional)"
      - "Food and drinks"
    
    # Booking options
    freeCancellation: true
    reserveNowPayLater: true
    instructorInfo: "English, Spanish"
    isPrivateGroup: true
    
    # Booking guarantees & payment
    bookingGuarantees:
      - "Instant confirmation"
      - "Flexible cancellation policy"
      - "Quick and easy reservation"
      - "Partial online payment"
    
    # Booking widget configuration
    bookingWidget:
      enableWidget: true
      bookingProductId: 219  # El ID del producto según la página web
      companyId: 1
      channelId: 19
      showQuantity: false
      bookNowLabel: "Reserve Now"
    
    # Marketing & reviews
    isBestSeller: true
    isLikelyToSellOut: true
    
    # Important information
    importantInformation: [
      {
        "_type": "block",
        "style": "normal",
        "children": [
          {
            "_type": "span",
            "text": "BOOKING AT LEAST 48 HOUR IN ADVANCE IS HIGHLY RECOMMENDED. FOR SAME OR NEXT DAY BOOKING CALL FIRST TO +34654082728 TO CHECK AVAILABILITY."
          }
        ]
      }
    ]
    
    # FAQs
    faqs:
      - question: "Do I need a license to rent this boat?"
        answer: "This boat can be rented with or without a skipper. If you don't have a license, you'll need to hire a skipper."
      - question: "Is fuel included in the price?"
        answer: "No, fuel is not included. Estimated cost is about 90€ per half day."
      - question: "How many people can the boat accommodate?"
        answer: "The boat can accommodate up to 6 people including the skipper."
      - question: "What months is this boat available?"
        answer: "The boat is available from May through October."
